//! The tempo map is generated from the tempo automation (TDD §6.2, §12.3).
//!
//! §12.3 is explicit: *"the tempo map is generated by evaluating the tempo
//! automation, so tempo automation and the tempo map are the same system
//! rather than two systems that must be kept in sync."* The document stores
//! the map the tempo box sets — one number, at tick 0 — and the lane bends it.
//! `effective_tempo_map` is where the two become one.

use fontelle_model::{
    Arena, AutomationData, AutomationPoint, Clip, ClipSource, CurveShape, Lane, Project, TempoMap,
    effective_tempo_map,
};
use fontelle_types::{PPQN, ParamTarget, Tick, normalised_tempo, tempo_from_normalised};

const SR: f64 = 48_000.0;
const BAR: Tick = PPQN * 4;

fn point(tick: Tick, bpm: f64) -> AutomationPoint {
    AutomationPoint {
        tick,
        value: normalised_tempo(bpm),
        curve: CurveShape::Linear,
        tension: 0.0,
    }
}

fn project_at(bpm: f64) -> Project {
    let mut project = Project::new("tempo");
    project.tempo_map = TempoMap::new(bpm, SR);
    project.lanes.insert(Lane {
        name: "Tempo".into(),
        height: 32.0,
        color: [0; 4],
        muted: false,
        locked: false,
        order: 0,
    });
    project
}

fn with_tempo_clip(project: &mut Project, start: Tick, length: Tick, points: Vec<AutomationPoint>) {
    let lane = project.lanes.keys().next().unwrap();
    let mut arena = Arena::default();
    for p in points {
        arena.insert(p);
    }
    project.clips.insert(Clip {
        lane,
        start,
        length,
        source: ClipSource::Automation(AutomationData {
            target: ParamTarget::Tempo.address(),
            points: arena,
        }),
        prefab_link: None,
        color: None,
        muted: false,
        loop_length: None,
    });
}

#[test]
fn with_no_tempo_lane_the_map_is_the_documents_own() {
    let project = project_at(97.0);
    let map = effective_tempo_map(&project);
    assert_eq!(map.segments(), project.tempo_map.segments());
    assert_eq!(
        map.tick_to_sample(BAR * 3),
        project.tempo_map.tick_to_sample(BAR * 3)
    );
}

#[test]
fn a_flat_lane_sets_the_tempo_across_the_clip_and_holds_it_after() {
    let mut project = project_at(120.0);
    with_tempo_clip(
        &mut project,
        BAR,
        BAR,
        vec![point(0, 90.0), point(BAR, 90.0)],
    );
    let map = effective_tempo_map(&project);

    // Before the clip the box's tempo stands: a clip cannot reach back in
    // time (the same rule `automation_at` follows).
    assert!((map.tempo_at(0) - 120.0).abs() < 1e-6);
    assert!((map.tempo_at(BAR - 1) - 120.0).abs() < 1e-6);
    // Inside it, the lane.
    assert!((map.tempo_at(BAR) - 90.0).abs() < 1e-6);
    assert!((map.tempo_at(BAR + PPQN) - 90.0).abs() < 1e-6);
    // And after it, §12.2's second rule: the last automated value holds.
    assert!((map.tempo_at(BAR * 10) - 90.0).abs() < 1e-6);
}

#[test]
fn a_ramp_becomes_a_run_of_segments_that_climb() {
    let mut project = project_at(120.0);
    with_tempo_clip(
        &mut project,
        0,
        BAR * 4,
        vec![point(0, 100.0), point(BAR * 4, 160.0)],
    );
    let map = effective_tempo_map(&project);

    let bpms: Vec<f64> = map.segments().iter().map(|s| s.bpm).collect();
    assert!(
        bpms.len() >= 16,
        "a four-bar ramp is many steps, got {}",
        bpms.len()
    );
    assert!(
        bpms.windows(2).all(|w| w[1] >= w[0]),
        "a rising lane must not fall anywhere: {bpms:?}"
    );
    assert!((map.tempo_at(0) - 100.0).abs() < 1e-6);
    assert!((map.tempo_at(BAR * 4) - 160.0).abs() < 1e-6);
    // Half way along, half way up — to within a step.
    assert!((map.tempo_at(BAR * 2) - 130.0).abs() < 2.0);
}

#[test]
fn the_steps_are_fine_enough_to_be_heard_as_a_ramp_and_few_enough_to_be_cheap() {
    // A sixteenth note or finer: coarser and a ritardando is a staircase.
    // And a flat lane costs one segment, not one per step.
    let mut project = project_at(120.0);
    with_tempo_clip(
        &mut project,
        0,
        BAR,
        vec![point(0, 100.0), point(BAR, 140.0)],
    );
    let ramp = effective_tempo_map(&project);
    let starts: Vec<Tick> = ramp.segments().iter().map(|s| s.start_tick).collect();
    let widest = starts.windows(2).map(|w| w[1] - w[0]).max().unwrap_or(0);
    assert!(
        widest <= PPQN / 4,
        "a step of {widest} ticks is coarser than a sixteenth"
    );

    let mut project = project_at(120.0);
    with_tempo_clip(
        &mut project,
        0,
        BAR * 8,
        vec![point(0, 100.0), point(BAR * 8, 100.0)],
    );
    let flat = effective_tempo_map(&project);
    assert!(
        flat.segments().len() <= 2,
        "a flat lane is one tempo, not {} segments",
        flat.segments().len()
    );
}

#[test]
fn a_muted_tempo_clip_changes_nothing() {
    let mut project = project_at(120.0);
    with_tempo_clip(&mut project, 0, BAR, vec![point(0, 60.0), point(BAR, 60.0)]);
    for clip in project.clips.values_mut() {
        clip.muted = true;
    }
    let map = effective_tempo_map(&project);
    assert!((map.tempo_at(PPQN) - 120.0).abs() < 1e-6);
}

#[test]
fn the_map_keeps_the_documents_sample_rate() {
    let mut project = project_at(120.0);
    project.tempo_map.set_sample_rate(96_000.0);
    with_tempo_clip(
        &mut project,
        0,
        BAR,
        vec![point(0, 120.0), point(BAR, 120.0)],
    );
    let map = effective_tempo_map(&project);
    assert_eq!(map.sample_rate_hz(), 96_000.0);
    // A quarter note at 120 is half a second, which is 48 000 samples here.
    assert_eq!(map.tick_to_sample(PPQN), 48_000);
}

#[test]
fn the_value_on_the_lane_is_the_tempo_the_box_would_show() {
    // The mapping is the one `fontelle_types` publishes, and nothing else:
    // a lane drawn at "120" has to *be* 120.
    let mut project = project_at(120.0);
    let v = normalised_tempo(133.0);
    with_tempo_clip(
        &mut project,
        0,
        BAR,
        vec![
            AutomationPoint {
                tick: 0,
                value: v,
                curve: CurveShape::Linear,
                tension: 0.0,
            },
            AutomationPoint {
                tick: BAR,
                value: v,
                curve: CurveShape::Linear,
                tension: 0.0,
            },
        ],
    );
    let map = effective_tempo_map(&project);
    assert!((map.tempo_at(PPQN) - tempo_from_normalised(v)).abs() < 1e-9);
    assert!((map.tempo_at(PPQN) - 133.0).abs() < 1e-6);
}
