//! INVARIANT 7, made usable: every automatable parameter has a stable string
//! address, and every effect can list the ones it has (TDD §8.2, §12.3).
//!
//! > *"Ensure we keep everything automatable — any value in these mixer
//! > effects I should be able to turn into an automation track in my
//! > timeline."*
//!
//! That is this file's whole subject, and §8.2 is emphatic about how it must
//! be done: **one** addressing scheme, serving plugin export, automation
//! targets, preset serialisation, MIDI learn and undo command targets. A
//! second, parallel scheme for any of them is a design regression.
//!
//! So an effect does not get a bespoke "which knobs does this have" list. It
//! answers one question — [`EffectConfig::specs`] — and every parameter it
//! names is addressable, readable, writable, and normalisable. An effect
//! parameter that automation cannot reach is a bug in this file's terms, and
//! `every_effect_parameter_is_reachable_by_address` is the test that says so.

use fontelle_types::{BandType, EffectConfig, EffectKind, ParamAddress, ParamTarget, Taper, Unit};

fn a_track() -> fontelle_types::MixerTrackId {
    fontelle_types::MixerTrackId::from(slotmap::KeyData::from_ffi((1 << 32) | 3))
}

// ------------------------------------------------------------- addressing

#[test]
fn an_inserts_parameter_addresses_the_way_the_tdd_writes_it() {
    // §8.2's own example, to the character: `mixer:<id>/insert[0]/param/<name>`.
    let address = ParamTarget::Insert {
        track: a_track(),
        slot: 0,
        param: "band1.freq".into(),
    }
    .address();
    assert_eq!(
        address.as_str(),
        format!("mixer:{}/insert[0]/param/band1.freq", a_track_id())
    );
}

fn a_track_id() -> u64 {
    use slotmap::Key;
    a_track().data().as_ffi()
}

#[test]
fn a_tracks_own_controls_address_too() {
    // §12.3: "every mixer track volume/pan/send level" is automatable.
    assert_eq!(
        ParamTarget::TrackGain(a_track()).address().as_str(),
        format!("mixer:{}/gain", a_track_id())
    );
    assert_eq!(
        ParamTarget::TrackPan(a_track()).address().as_str(),
        format!("mixer:{}/pan", a_track_id())
    );
}

#[test]
fn the_tempo_addresses_as_the_tdd_writes_it() {
    // §12.3 again: the tempo map is generated by evaluating tempo automation,
    // so the two are one system rather than two to keep in sync.
    assert_eq!(ParamTarget::Tempo.address().as_str(), "transport/tempo");
}

#[test]
fn every_address_parses_back_to_the_target_that_wrote_it() {
    // The round trip is what makes it one scheme rather than two: the string
    // is what is stored and the enum is a view of it, so a target that could
    // not be read back would be a second scheme wearing the first one's
    // clothes.
    for target in [
        ParamTarget::Tempo,
        ParamTarget::TrackGain(a_track()),
        ParamTarget::TrackPan(a_track()),
        ParamTarget::Insert {
            track: a_track(),
            slot: 3,
            param: "band7.q".into(),
        },
    ] {
        let address = target.address();
        assert_eq!(
            ParamTarget::parse(&address),
            Some(target.clone()),
            "{address} did not parse back"
        );
    }
}

#[test]
fn an_address_nobody_recognises_is_none_rather_than_a_guess() {
    for text in [
        "",
        "mixer",
        "mixer:notanumber/gain",
        "mixer:12/insert[x]/param/a",
        "channel:4/patch/layer[2]/filter1.cutoff",
        "transport/swing",
    ] {
        assert_eq!(
            ParamTarget::parse(&ParamAddress::new(text)),
            None,
            "{text} should not parse"
        );
    }
}

// -------------------------------------------------------- the effect's list

#[test]
fn an_eq_lists_every_band_it_has() {
    let config = EffectConfig::new(EffectKind::Eq);
    let specs = config.specs();
    // Frequency, gain, Q, on, type and channel, for each of eight bands.
    assert_eq!(specs.len(), 8 * 6, "eight bands, six controls each");
    for band in 1..=8 {
        for suffix in ["freq", "gain", "q", "on", "type", "channel"] {
            let id = format!("band{band}.{suffix}");
            assert!(
                specs.iter().any(|spec| spec.id == id),
                "{id} is not in the list"
            );
        }
    }
}

#[test]
fn every_parameter_has_a_name_a_range_and_a_default_inside_it() {
    // §8.2's list: stable ID, display name, range, default, unit, value
    // distribution. A parameter missing any of them is one a generic editor
    // cannot draw and automation cannot scale.
    for kind in EffectKind::ALL {
        for spec in EffectConfig::new(kind).specs() {
            assert!(!spec.id.is_empty(), "an id");
            assert!(!spec.name.is_empty(), "{} has no display name", spec.id);
            assert!(spec.max > spec.min, "{} has an empty range", spec.id);
            assert!(
                spec.default >= spec.min && spec.default <= spec.max,
                "{}'s default {} is outside {}..={}",
                spec.id,
                spec.default,
                spec.min,
                spec.max
            );
        }
    }
}

#[test]
fn every_parameter_id_is_unique_within_its_effect() {
    // Two parameters sharing an address is two automation lanes fighting over
    // one control, and the loser is whichever the reader happens to find
    // second.
    for kind in EffectKind::ALL {
        let config = EffectConfig::new(kind);
        let mut ids: Vec<&str> = config.specs().iter().map(|spec| spec.id).collect();
        let before = ids.len();
        ids.sort_unstable();
        ids.dedup();
        assert_eq!(ids.len(), before, "{kind:?} has a duplicate parameter id");
    }
}

// ------------------------------------------------------------ reading them

#[test]
fn every_effect_parameter_is_reachable_by_address() {
    // The user's sentence, as a test: *any* value in a mixer effect can be
    // turned into an automation lane. A parameter that `specs` lists and `get`
    // cannot read is a lane that would draw and do nothing.
    for kind in EffectKind::ALL {
        let config = EffectConfig::new(kind);
        for spec in config.specs() {
            assert!(
                config.get(spec.id).is_some(),
                "{kind:?}'s {} is listed and cannot be read",
                spec.id
            );
            assert!(
                config.normalised(spec.id).is_some(),
                "{kind:?}'s {} has no normalised value",
                spec.id
            );
        }
    }
}

#[test]
fn a_fresh_effect_reads_back_every_default_it_declared() {
    for kind in EffectKind::ALL {
        let config = EffectConfig::new(kind);
        for spec in config.specs() {
            let value = config.get(spec.id).unwrap();
            assert!(
                (value - spec.default).abs() < 1e-4,
                "{kind:?}'s {} declares {} and reads {value}",
                spec.id,
                spec.default
            );
        }
    }
}

#[test]
fn an_address_the_effect_does_not_have_reads_none() {
    let config = EffectConfig::new(EffectKind::Eq);
    assert_eq!(config.get("band9.freq"), None);
    assert_eq!(config.get("threshold"), None);
    assert_eq!(config.get(""), None);
}

// ------------------------------------------------------------ writing them

#[test]
fn every_parameter_can_be_written_and_read_back() {
    for kind in EffectKind::ALL {
        let mut config = EffectConfig::new(kind);
        for spec in EffectConfig::new(kind).specs() {
            // A quarter of the way up the range: inside it, and not the
            // default, so a `set` that did nothing fails here.
            let target = spec.min + (spec.max - spec.min) * 0.25;
            config.set(spec.id, target);
            let back = config.get(spec.id).unwrap();
            let tolerance = match spec.taper {
                // A stepped parameter lands on a step, not on the number asked
                // for, which is the whole point of it being stepped.
                Taper::Stepped(_) => (spec.max - spec.min) / 2.0,
                _ => (spec.max - spec.min) * 1e-3,
            };
            assert!(
                (back - target).abs() <= tolerance,
                "{kind:?}'s {} was set to {target} and reads {back}",
                spec.id
            );
        }
    }
}

#[test]
fn writing_past_an_end_of_the_range_stops_at_the_end() {
    // An automation curve reaching 1.0 must not be able to produce a filter
    // frequency of a million.
    for kind in EffectKind::ALL {
        let mut config = EffectConfig::new(kind);
        for spec in EffectConfig::new(kind).specs() {
            config.set(spec.id, spec.max * 100.0 + 1000.0);
            let high = config.get(spec.id).unwrap();
            assert!(high <= spec.max + 1e-3, "{} went past its top", spec.id);
            config.set(spec.id, spec.min - 1000.0);
            let low = config.get(spec.id).unwrap();
            assert!(low >= spec.min - 1e-3, "{} went past its bottom", spec.id);
        }
    }
}

#[test]
fn writing_one_parameter_leaves_the_others_where_they_were() {
    let mut config = EffectConfig::new(EffectKind::Eq);
    config.set("band3.gain", 6.0);
    for spec in EffectConfig::new(EffectKind::Eq).specs() {
        if spec.id == "band3.gain" {
            continue;
        }
        let value = config.get(spec.id).unwrap();
        assert!(
            (value - spec.default).abs() < 1e-4,
            "{} moved when band3.gain was written",
            spec.id
        );
    }
}

// --------------------------------------------------------- and normalised

#[test]
fn normalised_runs_zero_to_one_across_the_whole_range() {
    // What an automation point stores (§12.1: "value: f64, normalised 0..1"),
    // so the curve is the same shape whatever the parameter's units are.
    for kind in EffectKind::ALL {
        let mut config = EffectConfig::new(kind);
        for spec in EffectConfig::new(kind).specs() {
            config.set_normalised(spec.id, 0.0);
            assert!(
                (config.get(spec.id).unwrap() - spec.min).abs() <= (spec.max - spec.min) * 1e-3,
                "{} at 0.0 should be its minimum",
                spec.id
            );
            config.set_normalised(spec.id, 1.0);
            assert!(
                (config.get(spec.id).unwrap() - spec.max).abs() <= (spec.max - spec.min) * 1e-3,
                "{} at 1.0 should be its maximum",
                spec.id
            );
        }
    }
}

#[test]
fn a_normalised_value_survives_the_round_trip() {
    for kind in EffectKind::ALL {
        let mut config = EffectConfig::new(kind);
        for spec in EffectConfig::new(kind).specs() {
            if matches!(spec.taper, Taper::Stepped(_)) {
                continue; // lands on a step, by design
            }
            for t in [0.0, 0.25, 0.5, 0.75, 1.0] {
                config.set_normalised(spec.id, t);
                let back = config.normalised(spec.id).unwrap();
                assert!(
                    (back - t).abs() < 1e-3,
                    "{}: {t} came back as {back}",
                    spec.id
                );
            }
        }
    }
}

#[test]
fn a_frequency_is_normalised_logarithmically() {
    // Because that is how hearing works, and because a linear 20 Hz–20 kHz
    // automation lane spends nine tenths of its travel above 2 kHz. The middle
    // of a frequency's lane should land somewhere musical.
    let mut config = EffectConfig::new(EffectKind::Eq);
    config.set_normalised("band1.freq", 0.5);
    let middle = config.get("band1.freq").unwrap();
    assert!(
        (400.0..2_000.0).contains(&middle),
        "half way up a frequency lane should be mid-band, was {middle} Hz"
    );
}

#[test]
fn a_stepped_parameter_reaches_every_one_of_its_steps() {
    // A band type is a choice, and an automation lane over it has to be able
    // to name all eleven — not ten of them and a rounding error.
    let mut config = EffectConfig::new(EffectKind::Eq);
    let mut seen = Vec::new();
    for step in 0..64 {
        config.set_normalised("band1.type", step as f32 / 63.0);
        seen.push(config.get("band1.type").unwrap() as i32);
    }
    seen.sort_unstable();
    seen.dedup();
    assert_eq!(
        seen.len(),
        BandType::ALL.len(),
        "every band type should be reachable, got {seen:?}"
    );
}

// -------------------------------------------------------- and it is the EQ

#[test]
fn the_bands_addresses_move_the_band_they_name() {
    // The join between the two halves: the generic contract above and the
    // typed `EqConfig` the DSP reads. They are one value, so writing through
    // either is visible through the other.
    let mut config = EffectConfig::new(EffectKind::Eq);
    config.set("band2.freq", 500.0);
    config.set("band2.gain", -4.0);
    config.set("band2.on", 1.0);

    let EffectConfig::Eq(eq) = config else {
        unreachable!("this slot holds an EQ")
    };
    assert!((eq.bands[1].freq_hz - 500.0).abs() < 0.5);
    assert!((eq.bands[1].gain_db + 4.0).abs() < 0.01);
    assert!(eq.bands[1].enabled);
}

#[test]
fn a_unit_is_declared_so_a_lane_can_say_what_it_is_showing() {
    let config = EffectConfig::new(EffectKind::Eq);
    let spec = |id: &str| {
        config
            .specs()
            .iter()
            .find(|spec| spec.id == id)
            .copied()
            .unwrap()
    };
    assert_eq!(spec("band1.freq").unit, Unit::Hertz);
    assert_eq!(spec("band1.gain").unit, Unit::Decibels);
    assert_eq!(spec("band1.on").unit, Unit::Switch);
}
