//! Puts the factory presets in the binary (`docs/flopsynth-plan.md` §P.3).
//!
//! Forty lines rather than a crate, for the reason `fontelle-types`'
//! `base64.rs` is forty lines rather than a dependency: what this does is walk
//! a folder and write a list, and a dependency that walked it for us would be
//! a dependency to audit for the sake of six lines of recursion.
//!
//! The output is one generated file holding `(path, contents)` pairs, so a
//! factory preset is **present on a fresh install** with nothing to unpack —
//! the position the drum machine's constructor kits held and this keeps.
//!
//! The tree itself is written by `cargo xtask export-factory-presets`, which
//! is where the recipes that used to be constructor code now live. Nothing
//! here parses a preset: a malformed file is a build that still succeeds and
//! a test (`tests/preset_bank.rs`) that fails, which is the right place for
//! it to be caught, because the parser lives in the crate this is building.

use std::path::{Path, PathBuf};

fn main() {
    let root =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap()).join("../../assets/presets");
    // Re-run when a preset is added, removed or edited. The folder itself is
    // named too, so a *new* device folder is noticed and not only a changed
    // file inside one that already existed.
    println!("cargo:rerun-if-changed={}", root.display());

    let mut files = Vec::new();
    walk(&root, &root, &mut files);
    // Sorted, so the generated file is the same bytes for the same tree
    // whatever order the filesystem handed the entries back in — a build that
    // differs by directory order is a build nobody can reproduce.
    files.sort();

    let mut out = String::from(
        "// Generated by build.rs from assets/presets. Do not edit.\n\
         pub static FACTORY_PRESETS: &[(&str, &str)] = &[\n",
    );
    for (relative, absolute) in &files {
        println!("cargo:rerun-if-changed={}", absolute.display());
        out.push_str(&format!(
            "    ({relative:?}, include_str!({:?})),\n",
            absolute.display().to_string()
        ));
    }
    out.push_str("];\n");

    let generated = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("factory_presets.rs");
    std::fs::write(&generated, out).expect("the generated file must be writable");
}

/// Every `.json` under `dir`, as (path relative to the root, path on disk).
fn walk(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        // No tree at all is a legal state — a checkout before the export has
        // been run, and the bank simply ships nothing.
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            walk(root, &path, out);
        } else if path.extension().is_some_and(|e| e == "json") {
            let relative = path
                .strip_prefix(root)
                .expect("walked from the root")
                .to_string_lossy()
                // Forward slashes whatever built this, because the string is
                // read back as a preset's address and compared, not opened.
                .replace('\\', "/");
            out.push((relative, path));
        }
    }
}
